### PR TITLE
Add implementation that use new server APIs

### PR DESCRIPTION
**Pull request by petterarvidsson**
- There are still several hard coded values that should be made
  configurable

### CODE REVIEW

**Comment by petterarvidsson** [comment]
@nsg This is work in progress

**Comment by petterarvidsson** [comment]
This reuquires konstructs/server#97

**Comment by petterarvidsson** [comment]
@nsg Other than the server dependency I think this is now good enough to be merged. It works and forests can be triggered by konstructing a sapling and planting it.

**Comment by nsg** [comment]
@petterarvidsson nice! :+1:

**Pull request merged**
